palette = 'colors'

[palettes.colors]
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

format = "$directory$nix_shell$rust$lua$haskell$nodejs$git_branch$git_status\n$character"

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold color1)"

[git_branch]
style = "bold red"
symbol = ""

[git_status]
disabled = false

[haskell]
disabled = false
format = "via [󰲒 $version](bold purple)"

[lua]
format = "via [󰢱 $version](bold blue) "

[nix_shell]
disabled = false
format = "via [ $name](bold blue) "
impure_msg = ""
pure_msg = ""
unknown_msg = ""

[nodejs]
format = "via [󰎙 $version](bold green) "

[rust]
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]
format = "via [ $version](bold orange) "
version_format = "v$raw"
