[colors.primary]
background = '#0f1511'
foreground = '#dfe4dd'
 
[colors.cursor]
text = '#dfe4dd'
cursor = '#c0c9c0'
 
[colors.vi_mode_cursor]
text = '#0f1511'
cursor = '#92d5ab'
 
[colors.search.matches]
foreground = '#404942'
background = '#a3cddc'
 
[colors.search.focused_match]
foreground = '#404942'
background = '#92d5ab'
 
[colors.footer_bar]
foreground = '#404942'
background = '#dfe4dd'
 
[colors.hints.start]
foreground = '#404942'
background = '#b5ccbb'
 
[colors.hints.end]
foreground = '#404942'
background = '#b5ccbb'
 
[colors.selection]
text = '#0f1511'
background = '#92d5ab'
 
[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#92d5ab'
yellow = '#286a48'
blue = '#92d5ab'
magenta = '#a3cddc'
cyan = '#b5ccbb'
white = '#BAC2DE'
 
[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8' 
 
[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
