[managers.system]
items = [
  "discord",
  "hyprland",
  "hyprcursor",
  "hyprlock",
  "waybar",
  "firefox",
  "nushell",
  "starship",
  "ttf-jetbrains-mono-nerd",
  "grimblast-git",
  "fastfetch",
  "zoxide",
  "rustup",
  "waypaper",
  "wf-recorder",
  "swww",
  "pipewire",
  "pipewire-jack",
  "hypridle",
  "dunst",
  "clang",
  "cmatrix",
  "cava",
  "btop",
  "bat",
  "bibata-cursor-theme",
  "blueman",
  "lua",
  "lua-language-server",
  "nautilus",
  "noto-fonts",
  "noto-fonts-cjk",
  "noto-fonts-emoji",
  "noto-fonts-extra",
  "ripgrep",
  "fzf",
  "walker-bin",
  # "wallust",
  "kitty",
  "helix"
]
