[general]
import = ["./colors.toml"]

[window]
padding = { x = 14, y = 14 }
dynamic_padding = true

[cursor]
style.blinking = "always"
unfocused_hollow = false

[mouse]
hide_when_typing = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11
